#  Copyright (c) 2025, TensorCast Team.

# mypy: ignore-errors
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: communicator_config.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 0, "", "communicator_config.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x19\x63ommunicator_config.proto\x12\x17tensorcast.communicator"|\n\x0cStagerConfig\x12\x1a\n\x12stage_cpu_for_rdma\x18\x01 \x01(\x08\x12\x1a\n\x12stage_chunk_mb_cpu\x18\x02 \x01(\r\x12\x1a\n\x12stage_chunk_mb_gpu\x18\x03 \x01(\r\x12\x18\n\x10\x62uffers_per_flow\x18\x04 \x01(\x05"u\n\nRdmaConfig\x12\x16\n\x0eoutstanding_wr\x18\x01 \x01(\x05\x12\x12\n\nack_ttl_ms\x18\x02 \x01(\r\x12\x15\n\rtraffic_class\x18\x03 \x01(\x05\x12\x12\n\nqp_timeout\x18\x04 \x01(\x05\x12\x10\n\x08qp_retry\x18\x05 \x01(\x05"R\n\nPoolConfig\x12\x16\n\x0epreregister_mr\x18\x01 \x01(\x08\x12\x17\n\x0fpool_size_bytes\x18\x02 \x01(\x04\x12\x13\n\x0b\x63hunk_bytes\x18\x03 \x01(\x04"W\n\x0fTransportConfig\x12\x16\n\x0etcp_conn_count\x18\x01 \x01(\x05\x12\x0f\n\x07tcp_tos\x18\x02 \x01(\x05\x12\x1b\n\x13\x63onnect_timeout_sec\x18\x03 \x01(\x05" \n\x0e\x41\x66\x66inityConfig\x12\x0e\n\x06\x65nable\x18\x01 \x01(\x08"L\n\x0eSimpleNumaNode\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nics\x18\x02 \x03(\t\x12\x0c\n\x04gpus\x18\x03 \x03(\x05\x12\x12\n\nis_default\x18\x04 \x01(\x08"Z\n\x10SimpleNumaConfig\x12\x0e\n\x06\x65nable\x18\x01 \x01(\x08\x12\x36\n\x05nodes\x18\x02 \x03(\x0b\x32\'.tensorcast.communicator.SimpleNumaNode"\xfe\x02\n\x12\x43ommunicatorConfig\x12\x13\n\x0b\x65nable_rdma\x18\x01 \x01(\x08\x12\x35\n\x06stager\x18\x02 \x01(\x0b\x32%.tensorcast.communicator.StagerConfig\x12\x31\n\x04rdma\x18\x03 \x01(\x0b\x32#.tensorcast.communicator.RdmaConfig\x12\x31\n\x04pool\x18\x04 \x01(\x0b\x32#.tensorcast.communicator.PoolConfig\x12;\n\ttransport\x18\x05 \x01(\x0b\x32(.tensorcast.communicator.TransportConfig\x12\x39\n\x08\x61\x66\x66inity\x18\x06 \x01(\x0b\x32\'.tensorcast.communicator.AffinityConfig\x12>\n\x0bsimple_numa\x18\x07 \x01(\x0b\x32).tensorcast.communicator.SimpleNumaConfigb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "communicator_config_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_STAGERCONFIG"]._serialized_start = 54
    _globals["_STAGERCONFIG"]._serialized_end = 178
    _globals["_RDMACONFIG"]._serialized_start = 180
    _globals["_RDMACONFIG"]._serialized_end = 297
    _globals["_POOLCONFIG"]._serialized_start = 299
    _globals["_POOLCONFIG"]._serialized_end = 381
    _globals["_TRANSPORTCONFIG"]._serialized_start = 383
    _globals["_TRANSPORTCONFIG"]._serialized_end = 470
    _globals["_AFFINITYCONFIG"]._serialized_start = 472
    _globals["_AFFINITYCONFIG"]._serialized_end = 504
    _globals["_SIMPLENUMANODE"]._serialized_start = 506
    _globals["_SIMPLENUMANODE"]._serialized_end = 582
    _globals["_SIMPLENUMACONFIG"]._serialized_start = 584
    _globals["_SIMPLENUMACONFIG"]._serialized_end = 674
    _globals["_COMMUNICATORCONFIG"]._serialized_start = 677
    _globals["_COMMUNICATORCONFIG"]._serialized_end = 1059
# @@protoc_insertion_point(module_scope)
