# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

import tensorcast.proto.global_store_pb2 as global__store__pb2


class GlobalStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterReplica = channel.unary_unary(
            "/global_store.GlobalStore/RegisterReplica",
            request_serializer=global__store__pb2.RegisterReplicaRequest.SerializeToString,
            response_deserializer=global__store__pb2.RegisterReplicaResponse.FromString,
        )
        self.UpdateReplica = channel.unary_unary(
            "/global_store.GlobalStore/UpdateReplica",
            request_serializer=global__store__pb2.UpdateReplicaRequest.SerializeToString,
            response_deserializer=global__store__pb2.UpdateReplicaResponse.FromString,
        )
        self.UnregisterReplica = channel.unary_unary(
            "/global_store.GlobalStore/UnregisterReplica",
            request_serializer=global__store__pb2.UnregisterReplicaRequest.SerializeToString,
            response_deserializer=global__store__pb2.UnregisterReplicaResponse.FromString,
        )
        self.RequestReplicaTransport = channel.unary_unary(
            "/global_store.GlobalStore/RequestReplicaTransport",
            request_serializer=global__store__pb2.RequestReplicaTransportRequest.SerializeToString,
            response_deserializer=global__store__pb2.RequestReplicaTransportResponse.FromString,
        )
        self.CompleteReplicaTransport = channel.unary_unary(
            "/global_store.GlobalStore/CompleteReplicaTransport",
            request_serializer=global__store__pb2.CompleteReplicaTransportRequest.SerializeToString,
            response_deserializer=global__store__pb2.CompleteReplicaTransportResponse.FromString,
        )
        self.ListReplicas = channel.unary_unary(
            "/global_store.GlobalStore/ListReplicas",
            request_serializer=global__store__pb2.ListReplicasRequest.SerializeToString,
            response_deserializer=global__store__pb2.ListReplicasResponse.FromString,
        )
        self.GetArtifactInfoById = channel.unary_unary(
            "/global_store.GlobalStore/GetArtifactInfoById",
            request_serializer=global__store__pb2.GetArtifactInfoByIdRequest.SerializeToString,
            response_deserializer=global__store__pb2.GetArtifactInfoByIdResponse.FromString,
        )
        self.GetArtifactIndex = channel.unary_unary(
            "/global_store.GlobalStore/GetArtifactIndex",
            request_serializer=global__store__pb2.GetArtifactIndexRequest.SerializeToString,
            response_deserializer=global__store__pb2.GetArtifactIndexResponse.FromString,
        )
        self.RegisterWorker = channel.unary_unary(
            "/global_store.GlobalStore/RegisterWorker",
            request_serializer=global__store__pb2.RegisterWorkerRequest.SerializeToString,
            response_deserializer=global__store__pb2.RegisterWorkerResponse.FromString,
        )
        self.WorkerHeartbeat = channel.unary_unary(
            "/global_store.GlobalStore/WorkerHeartbeat",
            request_serializer=global__store__pb2.WorkerHeartbeatRequest.SerializeToString,
            response_deserializer=global__store__pb2.WorkerHeartbeatResponse.FromString,
        )
        self.UnregisterWorker = channel.unary_unary(
            "/global_store.GlobalStore/UnregisterWorker",
            request_serializer=global__store__pb2.UnregisterWorkerRequest.SerializeToString,
            response_deserializer=global__store__pb2.UnregisterWorkerResponse.FromString,
        )
        self.ListActiveWorkers = channel.unary_unary(
            "/global_store.GlobalStore/ListActiveWorkers",
            request_serializer=global__store__pb2.ListActiveWorkersRequest.SerializeToString,
            response_deserializer=global__store__pb2.ListActiveWorkersResponse.FromString,
        )
        self.SynchronizeWorkerState = channel.unary_unary(
            "/global_store.GlobalStore/SynchronizeWorkerState",
            request_serializer=global__store__pb2.SynchronizeWorkerStateRequest.SerializeToString,
            response_deserializer=global__store__pb2.SynchronizeWorkerStateResponse.FromString,
        )
        self.RequestFullStateSync = channel.unary_unary(
            "/global_store.GlobalStore/RequestFullStateSync",
            request_serializer=global__store__pb2.RequestFullStateSyncRequest.SerializeToString,
            response_deserializer=global__store__pb2.RequestFullStateSyncResponse.FromString,
        )
        self.HealthCheck = channel.unary_unary(
            "/global_store.GlobalStore/HealthCheck",
            request_serializer=global__store__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=global__store__pb2.HealthCheckResponse.FromString,
        )
        self.QueryChunkLocations = channel.unary_unary(
            "/global_store.GlobalStore/QueryChunkLocations",
            request_serializer=global__store__pb2.QueryChunkLocationsRequest.SerializeToString,
            response_deserializer=global__store__pb2.QueryChunkLocationsResponse.FromString,
        )
        self.BatchUpdateChunkStates = channel.unary_unary(
            "/global_store.GlobalStore/BatchUpdateChunkStates",
            request_serializer=global__store__pb2.BatchUpdateChunkStatesRequest.SerializeToString,
            response_deserializer=global__store__pb2.BatchUpdateChunkStatesResponse.FromString,
        )


class GlobalStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterReplica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateReplica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UnregisterReplica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RequestReplicaTransport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CompleteReplicaTransport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListReplicas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetArtifactInfoById(self, request, context):
        """Content-addressed query by artifact_id (mi2:...)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetArtifactIndex(self, request, context):
        """Get artifact tensor index data by key"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RegisterWorker(self, request, context):
        """Worker management"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def WorkerHeartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UnregisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListActiveWorkers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SynchronizeWorkerState(self, request, context):
        """High Availability and State Synchronization"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RequestFullStateSync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Health check endpoint"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def QueryChunkLocations(self, request, context):
        """========== Chunk Directory Operations ==========
        Query chunk locations for distributed memory pool
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def BatchUpdateChunkStates(self, request, context):
        """Update chunk states (called by StoreDaemon periodically)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_GlobalStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "RegisterReplica": grpc.unary_unary_rpc_method_handler(
            servicer.RegisterReplica,
            request_deserializer=global__store__pb2.RegisterReplicaRequest.FromString,
            response_serializer=global__store__pb2.RegisterReplicaResponse.SerializeToString,
        ),
        "UpdateReplica": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateReplica,
            request_deserializer=global__store__pb2.UpdateReplicaRequest.FromString,
            response_serializer=global__store__pb2.UpdateReplicaResponse.SerializeToString,
        ),
        "UnregisterReplica": grpc.unary_unary_rpc_method_handler(
            servicer.UnregisterReplica,
            request_deserializer=global__store__pb2.UnregisterReplicaRequest.FromString,
            response_serializer=global__store__pb2.UnregisterReplicaResponse.SerializeToString,
        ),
        "RequestReplicaTransport": grpc.unary_unary_rpc_method_handler(
            servicer.RequestReplicaTransport,
            request_deserializer=global__store__pb2.RequestReplicaTransportRequest.FromString,
            response_serializer=global__store__pb2.RequestReplicaTransportResponse.SerializeToString,
        ),
        "CompleteReplicaTransport": grpc.unary_unary_rpc_method_handler(
            servicer.CompleteReplicaTransport,
            request_deserializer=global__store__pb2.CompleteReplicaTransportRequest.FromString,
            response_serializer=global__store__pb2.CompleteReplicaTransportResponse.SerializeToString,
        ),
        "ListReplicas": grpc.unary_unary_rpc_method_handler(
            servicer.ListReplicas,
            request_deserializer=global__store__pb2.ListReplicasRequest.FromString,
            response_serializer=global__store__pb2.ListReplicasResponse.SerializeToString,
        ),
        "GetArtifactInfoById": grpc.unary_unary_rpc_method_handler(
            servicer.GetArtifactInfoById,
            request_deserializer=global__store__pb2.GetArtifactInfoByIdRequest.FromString,
            response_serializer=global__store__pb2.GetArtifactInfoByIdResponse.SerializeToString,
        ),
        "GetArtifactIndex": grpc.unary_unary_rpc_method_handler(
            servicer.GetArtifactIndex,
            request_deserializer=global__store__pb2.GetArtifactIndexRequest.FromString,
            response_serializer=global__store__pb2.GetArtifactIndexResponse.SerializeToString,
        ),
        "RegisterWorker": grpc.unary_unary_rpc_method_handler(
            servicer.RegisterWorker,
            request_deserializer=global__store__pb2.RegisterWorkerRequest.FromString,
            response_serializer=global__store__pb2.RegisterWorkerResponse.SerializeToString,
        ),
        "WorkerHeartbeat": grpc.unary_unary_rpc_method_handler(
            servicer.WorkerHeartbeat,
            request_deserializer=global__store__pb2.WorkerHeartbeatRequest.FromString,
            response_serializer=global__store__pb2.WorkerHeartbeatResponse.SerializeToString,
        ),
        "UnregisterWorker": grpc.unary_unary_rpc_method_handler(
            servicer.UnregisterWorker,
            request_deserializer=global__store__pb2.UnregisterWorkerRequest.FromString,
            response_serializer=global__store__pb2.UnregisterWorkerResponse.SerializeToString,
        ),
        "ListActiveWorkers": grpc.unary_unary_rpc_method_handler(
            servicer.ListActiveWorkers,
            request_deserializer=global__store__pb2.ListActiveWorkersRequest.FromString,
            response_serializer=global__store__pb2.ListActiveWorkersResponse.SerializeToString,
        ),
        "SynchronizeWorkerState": grpc.unary_unary_rpc_method_handler(
            servicer.SynchronizeWorkerState,
            request_deserializer=global__store__pb2.SynchronizeWorkerStateRequest.FromString,
            response_serializer=global__store__pb2.SynchronizeWorkerStateResponse.SerializeToString,
        ),
        "RequestFullStateSync": grpc.unary_unary_rpc_method_handler(
            servicer.RequestFullStateSync,
            request_deserializer=global__store__pb2.RequestFullStateSyncRequest.FromString,
            response_serializer=global__store__pb2.RequestFullStateSyncResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=global__store__pb2.HealthCheckRequest.FromString,
            response_serializer=global__store__pb2.HealthCheckResponse.SerializeToString,
        ),
        "QueryChunkLocations": grpc.unary_unary_rpc_method_handler(
            servicer.QueryChunkLocations,
            request_deserializer=global__store__pb2.QueryChunkLocationsRequest.FromString,
            response_serializer=global__store__pb2.QueryChunkLocationsResponse.SerializeToString,
        ),
        "BatchUpdateChunkStates": grpc.unary_unary_rpc_method_handler(
            servicer.BatchUpdateChunkStates,
            request_deserializer=global__store__pb2.BatchUpdateChunkStatesRequest.FromString,
            response_serializer=global__store__pb2.BatchUpdateChunkStatesResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "global_store.GlobalStore", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class GlobalStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterReplica(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/global_store.GlobalStore/RegisterReplica",
            global__store__pb2.RegisterReplicaRequest.SerializeToString,
            global__store__pb2.RegisterReplicaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def UpdateReplica(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/global_store.GlobalStore/UpdateReplica",
            global__store__pb2.UpdateReplicaRequest.SerializeToString,
            global__store__pb2.UpdateReplicaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def UnregisterReplica(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/global_store.GlobalStore/UnregisterReplica",
            global__store__pb2.UnregisterReplicaRequest.SerializeToString,
            global__store__pb2.UnregisterReplicaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def RequestReplicaTransport(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/global_store.GlobalStore/RequestReplicaTransport",
            global__store__pb2.RequestReplicaTransportRequest.SerializeToString,
            global__store__pb2.RequestReplicaTransportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def CompleteReplicaTransport(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/global_store.GlobalStore/CompleteReplicaTransport",
            global__store__pb2.CompleteReplicaTransportRequest.SerializeToString,
            global__store__pb2.CompleteReplicaTransportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ListReplicas(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/global_store.GlobalStore/ListReplicas",
            global__store__pb2.ListReplicasRequest.SerializeToString,
            global__store__pb2.ListReplicasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetArtifactInfoById(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/global_store.GlobalStore/GetArtifactInfoById",
            global__store__pb2.GetArtifactInfoByIdRequest.SerializeToString,
            global__store__pb2.GetArtifactInfoByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetArtifactIndex(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/global_store.GlobalStore/GetArtifactIndex",
            global__store__pb2.GetArtifactIndexRequest.SerializeToString,
            global__store__pb2.GetArtifactIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def RegisterWorker(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/global_store.GlobalStore/RegisterWorker",
            global__store__pb2.RegisterWorkerRequest.SerializeToString,
            global__store__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def WorkerHeartbeat(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/global_store.GlobalStore/WorkerHeartbeat",
            global__store__pb2.WorkerHeartbeatRequest.SerializeToString,
            global__store__pb2.WorkerHeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def UnregisterWorker(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/global_store.GlobalStore/UnregisterWorker",
            global__store__pb2.UnregisterWorkerRequest.SerializeToString,
            global__store__pb2.UnregisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ListActiveWorkers(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/global_store.GlobalStore/ListActiveWorkers",
            global__store__pb2.ListActiveWorkersRequest.SerializeToString,
            global__store__pb2.ListActiveWorkersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def SynchronizeWorkerState(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/global_store.GlobalStore/SynchronizeWorkerState",
            global__store__pb2.SynchronizeWorkerStateRequest.SerializeToString,
            global__store__pb2.SynchronizeWorkerStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def RequestFullStateSync(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/global_store.GlobalStore/RequestFullStateSync",
            global__store__pb2.RequestFullStateSyncRequest.SerializeToString,
            global__store__pb2.RequestFullStateSyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/global_store.GlobalStore/HealthCheck",
            global__store__pb2.HealthCheckRequest.SerializeToString,
            global__store__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def QueryChunkLocations(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/global_store.GlobalStore/QueryChunkLocations",
            global__store__pb2.QueryChunkLocationsRequest.SerializeToString,
            global__store__pb2.QueryChunkLocationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def BatchUpdateChunkStates(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/global_store.GlobalStore/BatchUpdateChunkStates",
            global__store__pb2.BatchUpdateChunkStatesRequest.SerializeToString,
            global__store__pb2.BatchUpdateChunkStatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
