#  Copyright (c) 2025, TensorCast Team.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

import tensorcast.proto.store_daemon_pb2 as store__daemon__pb2

GRPC_GENERATED_VERSION = "1.73.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in store_daemon_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class StoreDaemonStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MaterializeReplica = channel.unary_unary(
            "/store_daemon.StoreDaemon/MaterializeReplica",
            request_serializer=store__daemon__pb2.MaterializeReplicaRequest.SerializeToString,
            response_deserializer=store__daemon__pb2.MaterializeReplicaResponse.FromString,
            _registered_method=True,
        )
        self.ConfirmReplica = channel.unary_unary(
            "/store_daemon.StoreDaemon/ConfirmReplica",
            request_serializer=store__daemon__pb2.ConfirmReplicaRequest.SerializeToString,
            response_deserializer=store__daemon__pb2.ConfirmReplicaResponse.FromString,
            _registered_method=True,
        )
        self.UnloadReplica = channel.unary_unary(
            "/store_daemon.StoreDaemon/UnloadReplica",
            request_serializer=store__daemon__pb2.UnloadReplicaRequest.SerializeToString,
            response_deserializer=store__daemon__pb2.UnloadReplicaResponse.FromString,
            _registered_method=True,
        )
        self.ClearMem = channel.unary_unary(
            "/store_daemon.StoreDaemon/ClearMem",
            request_serializer=store__daemon__pb2.ClearMemRequest.SerializeToString,
            response_deserializer=store__daemon__pb2.ClearMemResponse.FromString,
            _registered_method=True,
        )
        self.GetServerConfig = channel.unary_unary(
            "/store_daemon.StoreDaemon/GetServerConfig",
            request_serializer=store__daemon__pb2.GetServerConfigRequest.SerializeToString,
            response_deserializer=store__daemon__pb2.GetServerConfigResponse.FromString,
            _registered_method=True,
        )
        self.GetWorkerStatus = channel.unary_unary(
            "/store_daemon.StoreDaemon/GetWorkerStatus",
            request_serializer=store__daemon__pb2.GetWorkerStatusRequest.SerializeToString,
            response_deserializer=store__daemon__pb2.GetWorkerStatusResponse.FromString,
            _registered_method=True,
        )
        self.WaitReplicaVerification = channel.unary_unary(
            "/store_daemon.StoreDaemon/WaitReplicaVerification",
            request_serializer=store__daemon__pb2.ReplicaVerificationRequest.SerializeToString,
            response_deserializer=store__daemon__pb2.ReplicaVerificationResponse.FromString,
            _registered_method=True,
        )
        self.GetDetailedStatus = channel.unary_unary(
            "/store_daemon.StoreDaemon/GetDetailedStatus",
            request_serializer=store__daemon__pb2.GetDetailedStatusRequest.SerializeToString,
            response_deserializer=store__daemon__pb2.GetDetailedStatusResponse.FromString,
            _registered_method=True,
        )
        self.GetLoadedReplicas = channel.unary_unary(
            "/store_daemon.StoreDaemon/GetLoadedReplicas",
            request_serializer=store__daemon__pb2.GetLoadedReplicasRequest.SerializeToString,
            response_deserializer=store__daemon__pb2.GetLoadedReplicasResponse.FromString,
            _registered_method=True,
        )
        self.LockTransportChunks = channel.unary_unary(
            "/store_daemon.StoreDaemon/LockTransportChunks",
            request_serializer=store__daemon__pb2.LockChunksRequest.SerializeToString,
            response_deserializer=store__daemon__pb2.LockChunksResponse.FromString,
            _registered_method=True,
        )
        self.UnlockTransportChunks = channel.unary_unary(
            "/store_daemon.StoreDaemon/UnlockTransportChunks",
            request_serializer=store__daemon__pb2.UnlockChunksRequest.SerializeToString,
            response_deserializer=store__daemon__pb2.UnlockChunksResponse.FromString,
            _registered_method=True,
        )
        self.BeginRegisterArtifact = channel.unary_unary(
            "/store_daemon.StoreDaemon/BeginRegisterArtifact",
            request_serializer=store__daemon__pb2.BeginRegisterArtifactRequest.SerializeToString,
            response_deserializer=store__daemon__pb2.BeginRegisterArtifactResponse.FromString,
            _registered_method=True,
        )
        self.CommitRegisteredArtifact = channel.unary_unary(
            "/store_daemon.StoreDaemon/CommitRegisteredArtifact",
            request_serializer=store__daemon__pb2.CommitRegisteredArtifactRequest.SerializeToString,
            response_deserializer=store__daemon__pb2.CommitRegisteredArtifactResponse.FromString,
            _registered_method=True,
        )
        self.AbortRegisteredArtifact = channel.unary_unary(
            "/store_daemon.StoreDaemon/AbortRegisteredArtifact",
            request_serializer=store__daemon__pb2.AbortRegisteredArtifactRequest.SerializeToString,
            response_deserializer=store__daemon__pb2.AbortRegisteredArtifactResponse.FromString,
            _registered_method=True,
        )


class StoreDaemonServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MaterializeReplica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ConfirmReplica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UnloadReplica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ClearMem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetServerConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetWorkerStatus(self, request, context):
        """Worker健康检测"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def WaitReplicaVerification(self, request, context):
        """------------------------------------------------------------------
        Asynchronous artifact integrity verification support.  Each MaterializeReplica
        request triggers a background verification task on the daemon side.
        Clients can poll/wait for the outcome via this RPC.
        ------------------------------------------------------------------

        Wait until the daemon finishes verifying the specified artifact replica
        (identified by the <artifact_id, replica_uuid> tuple) or the
        provided timeout elapses.  The call returns the current verification
        status so that clients can decide whether to retry or abort.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetDetailedStatus(self, request, context):
        """获取详细状态信息（以 Artifact/Replica 术语为准）"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetLoadedReplicas(self, request, context):
        """Get reference information for all loaded replicas"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def LockTransportChunks(self, request, context):
        """========== Distributed chunk locking ==========
        Dual-end locking mechanism for P2P transfers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UnlockTransportChunks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def BeginRegisterArtifact(self, request, context):
        """========== Memory Artifact Registration ==========
        New canonical RPC names
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CommitRegisteredArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AbortRegisteredArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_StoreDaemonServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "MaterializeReplica": grpc.unary_unary_rpc_method_handler(
            servicer.MaterializeReplica,
            request_deserializer=store__daemon__pb2.MaterializeReplicaRequest.FromString,
            response_serializer=store__daemon__pb2.MaterializeReplicaResponse.SerializeToString,
        ),
        "ConfirmReplica": grpc.unary_unary_rpc_method_handler(
            servicer.ConfirmReplica,
            request_deserializer=store__daemon__pb2.ConfirmReplicaRequest.FromString,
            response_serializer=store__daemon__pb2.ConfirmReplicaResponse.SerializeToString,
        ),
        "UnloadReplica": grpc.unary_unary_rpc_method_handler(
            servicer.UnloadReplica,
            request_deserializer=store__daemon__pb2.UnloadReplicaRequest.FromString,
            response_serializer=store__daemon__pb2.UnloadReplicaResponse.SerializeToString,
        ),
        "ClearMem": grpc.unary_unary_rpc_method_handler(
            servicer.ClearMem,
            request_deserializer=store__daemon__pb2.ClearMemRequest.FromString,
            response_serializer=store__daemon__pb2.ClearMemResponse.SerializeToString,
        ),
        "GetServerConfig": grpc.unary_unary_rpc_method_handler(
            servicer.GetServerConfig,
            request_deserializer=store__daemon__pb2.GetServerConfigRequest.FromString,
            response_serializer=store__daemon__pb2.GetServerConfigResponse.SerializeToString,
        ),
        "GetWorkerStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetWorkerStatus,
            request_deserializer=store__daemon__pb2.GetWorkerStatusRequest.FromString,
            response_serializer=store__daemon__pb2.GetWorkerStatusResponse.SerializeToString,
        ),
        "WaitReplicaVerification": grpc.unary_unary_rpc_method_handler(
            servicer.WaitReplicaVerification,
            request_deserializer=store__daemon__pb2.ReplicaVerificationRequest.FromString,
            response_serializer=store__daemon__pb2.ReplicaVerificationResponse.SerializeToString,
        ),
        "GetDetailedStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetDetailedStatus,
            request_deserializer=store__daemon__pb2.GetDetailedStatusRequest.FromString,
            response_serializer=store__daemon__pb2.GetDetailedStatusResponse.SerializeToString,
        ),
        "GetLoadedReplicas": grpc.unary_unary_rpc_method_handler(
            servicer.GetLoadedReplicas,
            request_deserializer=store__daemon__pb2.GetLoadedReplicasRequest.FromString,
            response_serializer=store__daemon__pb2.GetLoadedReplicasResponse.SerializeToString,
        ),
        "LockTransportChunks": grpc.unary_unary_rpc_method_handler(
            servicer.LockTransportChunks,
            request_deserializer=store__daemon__pb2.LockChunksRequest.FromString,
            response_serializer=store__daemon__pb2.LockChunksResponse.SerializeToString,
        ),
        "UnlockTransportChunks": grpc.unary_unary_rpc_method_handler(
            servicer.UnlockTransportChunks,
            request_deserializer=store__daemon__pb2.UnlockChunksRequest.FromString,
            response_serializer=store__daemon__pb2.UnlockChunksResponse.SerializeToString,
        ),
        "BeginRegisterArtifact": grpc.unary_unary_rpc_method_handler(
            servicer.BeginRegisterArtifact,
            request_deserializer=store__daemon__pb2.BeginRegisterArtifactRequest.FromString,
            response_serializer=store__daemon__pb2.BeginRegisterArtifactResponse.SerializeToString,
        ),
        "CommitRegisteredArtifact": grpc.unary_unary_rpc_method_handler(
            servicer.CommitRegisteredArtifact,
            request_deserializer=store__daemon__pb2.CommitRegisteredArtifactRequest.FromString,
            response_serializer=store__daemon__pb2.CommitRegisteredArtifactResponse.SerializeToString,
        ),
        "AbortRegisteredArtifact": grpc.unary_unary_rpc_method_handler(
            servicer.AbortRegisteredArtifact,
            request_deserializer=store__daemon__pb2.AbortRegisteredArtifactRequest.FromString,
            response_serializer=store__daemon__pb2.AbortRegisteredArtifactResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "store_daemon.StoreDaemon", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "store_daemon.StoreDaemon", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class StoreDaemon(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MaterializeReplica(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/store_daemon.StoreDaemon/MaterializeReplica",
            store__daemon__pb2.MaterializeReplicaRequest.SerializeToString,
            store__daemon__pb2.MaterializeReplicaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ConfirmReplica(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/store_daemon.StoreDaemon/ConfirmReplica",
            store__daemon__pb2.ConfirmReplicaRequest.SerializeToString,
            store__daemon__pb2.ConfirmReplicaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UnloadReplica(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/store_daemon.StoreDaemon/UnloadReplica",
            store__daemon__pb2.UnloadReplicaRequest.SerializeToString,
            store__daemon__pb2.UnloadReplicaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ClearMem(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/store_daemon.StoreDaemon/ClearMem",
            store__daemon__pb2.ClearMemRequest.SerializeToString,
            store__daemon__pb2.ClearMemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetServerConfig(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/store_daemon.StoreDaemon/GetServerConfig",
            store__daemon__pb2.GetServerConfigRequest.SerializeToString,
            store__daemon__pb2.GetServerConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetWorkerStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/store_daemon.StoreDaemon/GetWorkerStatus",
            store__daemon__pb2.GetWorkerStatusRequest.SerializeToString,
            store__daemon__pb2.GetWorkerStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def WaitReplicaVerification(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/store_daemon.StoreDaemon/WaitReplicaVerification",
            store__daemon__pb2.ReplicaVerificationRequest.SerializeToString,
            store__daemon__pb2.ReplicaVerificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetDetailedStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/store_daemon.StoreDaemon/GetDetailedStatus",
            store__daemon__pb2.GetDetailedStatusRequest.SerializeToString,
            store__daemon__pb2.GetDetailedStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetLoadedReplicas(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/store_daemon.StoreDaemon/GetLoadedReplicas",
            store__daemon__pb2.GetLoadedReplicasRequest.SerializeToString,
            store__daemon__pb2.GetLoadedReplicasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def LockTransportChunks(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/store_daemon.StoreDaemon/LockTransportChunks",
            store__daemon__pb2.LockChunksRequest.SerializeToString,
            store__daemon__pb2.LockChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UnlockTransportChunks(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/store_daemon.StoreDaemon/UnlockTransportChunks",
            store__daemon__pb2.UnlockChunksRequest.SerializeToString,
            store__daemon__pb2.UnlockChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def BeginRegisterArtifact(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/store_daemon.StoreDaemon/BeginRegisterArtifact",
            store__daemon__pb2.BeginRegisterArtifactRequest.SerializeToString,
            store__daemon__pb2.BeginRegisterArtifactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CommitRegisteredArtifact(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/store_daemon.StoreDaemon/CommitRegisteredArtifact",
            store__daemon__pb2.CommitRegisteredArtifactRequest.SerializeToString,
            store__daemon__pb2.CommitRegisteredArtifactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AbortRegisteredArtifact(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/store_daemon.StoreDaemon/AbortRegisteredArtifact",
            store__daemon__pb2.AbortRegisteredArtifactRequest.SerializeToString,
            store__daemon__pb2.AbortRegisteredArtifactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
