// Copyright (c) 2025, TensorCast Team.

// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/global_store.proto

#ifndef GRPC_MOCK_proto_2fglobal_5fstore_2eproto__INCLUDED
#define GRPC_MOCK_proto_2fglobal_5fstore_2eproto__INCLUDED

#include "proto/global_store.grpc.pb.h"
#include "proto/global_store.pb.h"

#include <gmock/gmock.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/sync_stream.h>
namespace global_store {

class MockGlobalStoreStub : public GlobalStore::StubInterface {
 public:
  MOCK_METHOD3(
      RegisterReplica,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::RegisterReplicaRequest& request,
          ::global_store::RegisterReplicaResponse* response));
  MOCK_METHOD3(
      AsyncRegisterReplicaRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::RegisterReplicaResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::RegisterReplicaRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncRegisterReplicaRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::RegisterReplicaResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::RegisterReplicaRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      UpdateReplica,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::UpdateReplicaRequest& request,
          ::global_store::UpdateReplicaResponse* response));
  MOCK_METHOD3(
      AsyncUpdateReplicaRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::UpdateReplicaResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::UpdateReplicaRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncUpdateReplicaRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::UpdateReplicaResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::UpdateReplicaRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      UnregisterReplica,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::UnregisterReplicaRequest& request,
          ::global_store::UnregisterReplicaResponse* response));
  MOCK_METHOD3(
      AsyncUnregisterReplicaRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::UnregisterReplicaResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::UnregisterReplicaRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncUnregisterReplicaRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::UnregisterReplicaResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::UnregisterReplicaRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      RequestReplicaTransport,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::RequestReplicaTransportRequest& request,
          ::global_store::RequestReplicaTransportResponse* response));
  MOCK_METHOD3(
      AsyncRequestReplicaTransportRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::RequestReplicaTransportResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::RequestReplicaTransportRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncRequestReplicaTransportRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::RequestReplicaTransportResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::RequestReplicaTransportRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      CompleteReplicaTransport,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::CompleteReplicaTransportRequest& request,
          ::global_store::CompleteReplicaTransportResponse* response));
  MOCK_METHOD3(
      AsyncCompleteReplicaTransportRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::CompleteReplicaTransportResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::CompleteReplicaTransportRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncCompleteReplicaTransportRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::CompleteReplicaTransportResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::CompleteReplicaTransportRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      ListReplicas,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::ListReplicasRequest& request,
          ::global_store::ListReplicasResponse* response));
  MOCK_METHOD3(
      AsyncListReplicasRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::ListReplicasResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::ListReplicasRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncListReplicasRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::ListReplicasResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::ListReplicasRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      GetArtifactInfoById,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::GetArtifactInfoByIdRequest& request,
          ::global_store::GetArtifactInfoByIdResponse* response));
  MOCK_METHOD3(
      AsyncGetArtifactInfoByIdRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::GetArtifactInfoByIdResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::GetArtifactInfoByIdRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncGetArtifactInfoByIdRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::GetArtifactInfoByIdResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::GetArtifactInfoByIdRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      GetArtifactIndex,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::GetArtifactIndexRequest& request,
          ::global_store::GetArtifactIndexResponse* response));
  MOCK_METHOD3(
      AsyncGetArtifactIndexRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::GetArtifactIndexResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::GetArtifactIndexRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncGetArtifactIndexRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::GetArtifactIndexResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::GetArtifactIndexRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      RegisterWorker,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::RegisterWorkerRequest& request,
          ::global_store::RegisterWorkerResponse* response));
  MOCK_METHOD3(
      AsyncRegisterWorkerRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::RegisterWorkerResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::RegisterWorkerRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncRegisterWorkerRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::RegisterWorkerResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::RegisterWorkerRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      WorkerHeartbeat,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::WorkerHeartbeatRequest& request,
          ::global_store::WorkerHeartbeatResponse* response));
  MOCK_METHOD3(
      AsyncWorkerHeartbeatRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::WorkerHeartbeatResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::WorkerHeartbeatRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncWorkerHeartbeatRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::WorkerHeartbeatResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::WorkerHeartbeatRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      UnregisterWorker,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::UnregisterWorkerRequest& request,
          ::global_store::UnregisterWorkerResponse* response));
  MOCK_METHOD3(
      AsyncUnregisterWorkerRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::UnregisterWorkerResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::UnregisterWorkerRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncUnregisterWorkerRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::UnregisterWorkerResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::UnregisterWorkerRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      ListActiveWorkers,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::ListActiveWorkersRequest& request,
          ::global_store::ListActiveWorkersResponse* response));
  MOCK_METHOD3(
      AsyncListActiveWorkersRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::ListActiveWorkersResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::ListActiveWorkersRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncListActiveWorkersRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::ListActiveWorkersResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::ListActiveWorkersRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      SynchronizeWorkerState,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::SynchronizeWorkerStateRequest& request,
          ::global_store::SynchronizeWorkerStateResponse* response));
  MOCK_METHOD3(
      AsyncSynchronizeWorkerStateRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::SynchronizeWorkerStateResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::SynchronizeWorkerStateRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncSynchronizeWorkerStateRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::SynchronizeWorkerStateResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::SynchronizeWorkerStateRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      RequestFullStateSync,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::RequestFullStateSyncRequest& request,
          ::global_store::RequestFullStateSyncResponse* response));
  MOCK_METHOD3(
      AsyncRequestFullStateSyncRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::RequestFullStateSyncResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::RequestFullStateSyncRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncRequestFullStateSyncRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::RequestFullStateSyncResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::RequestFullStateSyncRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      HealthCheck,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::HealthCheckRequest& request,
          ::global_store::HealthCheckResponse* response));
  MOCK_METHOD3(
      AsyncHealthCheckRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::HealthCheckResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::HealthCheckRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncHealthCheckRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::HealthCheckResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::HealthCheckRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      QueryChunkLocations,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::QueryChunkLocationsRequest& request,
          ::global_store::QueryChunkLocationsResponse* response));
  MOCK_METHOD3(
      AsyncQueryChunkLocationsRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::QueryChunkLocationsResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::QueryChunkLocationsRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncQueryChunkLocationsRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::QueryChunkLocationsResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::QueryChunkLocationsRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      BatchUpdateChunkStates,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::BatchUpdateChunkStatesRequest& request,
          ::global_store::BatchUpdateChunkStatesResponse* response));
  MOCK_METHOD3(
      AsyncBatchUpdateChunkStatesRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::BatchUpdateChunkStatesResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::BatchUpdateChunkStatesRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncBatchUpdateChunkStatesRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::BatchUpdateChunkStatesResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::BatchUpdateChunkStatesRequest& request,
          ::grpc::CompletionQueue* cq));
};

} // namespace global_store

#endif // GRPC_MOCK_proto_2fglobal_5fstore_2eproto__INCLUDED
