// Copyright (c) 2025, StepCast Team. All rights reserved.

// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/global_store.proto

#ifndef GRPC_MOCK_proto_2fglobal_5fstore_2eproto__INCLUDED
#define GRPC_MOCK_proto_2fglobal_5fstore_2eproto__INCLUDED

#include "proto/global_store.grpc.pb.h"
#include "proto/global_store.pb.h"

#include <gmock/gmock.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/sync_stream.h>
namespace global_store {

class MockGlobalModelStoreStub : public GlobalModelStore::StubInterface {
 public:
  MOCK_METHOD3(
      RegisterModelReplica,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::RegisterModelReplicaRequest& request,
          ::global_store::RegisterModelReplicaResponse* response));
  MOCK_METHOD3(
      AsyncRegisterModelReplicaRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::RegisterModelReplicaResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::RegisterModelReplicaRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncRegisterModelReplicaRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::RegisterModelReplicaResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::RegisterModelReplicaRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      UpdateModelReplica,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::UpdateModelReplicaRequest& request,
          ::global_store::UpdateModelReplicaResponse* response));
  MOCK_METHOD3(
      AsyncUpdateModelReplicaRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::UpdateModelReplicaResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::UpdateModelReplicaRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncUpdateModelReplicaRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::UpdateModelReplicaResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::UpdateModelReplicaRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      UnregisterModelReplica,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::UnregisterModelReplicaRequest& request,
          ::global_store::UnregisterModelReplicaResponse* response));
  MOCK_METHOD3(
      AsyncUnregisterModelReplicaRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::UnregisterModelReplicaResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::UnregisterModelReplicaRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncUnregisterModelReplicaRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::UnregisterModelReplicaResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::UnregisterModelReplicaRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      RequestModelReplicaTransport,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::RequestModelReplicaTransportRequest& request,
          ::global_store::RequestModelReplicaTransportResponse* response));
  MOCK_METHOD3(
      AsyncRequestModelReplicaTransportRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::RequestModelReplicaTransportResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::RequestModelReplicaTransportRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncRequestModelReplicaTransportRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::RequestModelReplicaTransportResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::RequestModelReplicaTransportRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      CompleteModelReplicaTransport,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::CompleteModelReplicaTransportRequest& request,
          ::global_store::CompleteModelReplicaTransportResponse* response));
  MOCK_METHOD3(
      AsyncCompleteModelReplicaTransportRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::CompleteModelReplicaTransportResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::CompleteModelReplicaTransportRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncCompleteModelReplicaTransportRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::CompleteModelReplicaTransportResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::CompleteModelReplicaTransportRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      ListModelReplicas,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::ListModelReplicasRequest& request,
          ::global_store::ListModelReplicasResponse* response));
  MOCK_METHOD3(
      AsyncListModelReplicasRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::ListModelReplicasResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::ListModelReplicasRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncListModelReplicasRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::ListModelReplicasResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::ListModelReplicasRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      GetModelInfo,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::GetModelInfoRequest& request,
          ::global_store::GetModelInfoResponse* response));
  MOCK_METHOD3(
      AsyncGetModelInfoRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::GetModelInfoResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::GetModelInfoRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncGetModelInfoRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::GetModelInfoResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::GetModelInfoRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      GetModelIndex,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::GetModelIndexRequest& request,
          ::global_store::GetModelIndexResponse* response));
  MOCK_METHOD3(
      AsyncGetModelIndexRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::GetModelIndexResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::GetModelIndexRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncGetModelIndexRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::GetModelIndexResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::GetModelIndexRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      RegisterWorker,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::RegisterWorkerRequest& request,
          ::global_store::RegisterWorkerResponse* response));
  MOCK_METHOD3(
      AsyncRegisterWorkerRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::RegisterWorkerResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::RegisterWorkerRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncRegisterWorkerRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::RegisterWorkerResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::RegisterWorkerRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      WorkerHeartbeat,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::WorkerHeartbeatRequest& request,
          ::global_store::WorkerHeartbeatResponse* response));
  MOCK_METHOD3(
      AsyncWorkerHeartbeatRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::WorkerHeartbeatResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::WorkerHeartbeatRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncWorkerHeartbeatRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::WorkerHeartbeatResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::WorkerHeartbeatRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      UnregisterWorker,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::UnregisterWorkerRequest& request,
          ::global_store::UnregisterWorkerResponse* response));
  MOCK_METHOD3(
      AsyncUnregisterWorkerRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::UnregisterWorkerResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::UnregisterWorkerRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncUnregisterWorkerRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::UnregisterWorkerResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::UnregisterWorkerRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      ListActiveWorkers,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::ListActiveWorkersRequest& request,
          ::global_store::ListActiveWorkersResponse* response));
  MOCK_METHOD3(
      AsyncListActiveWorkersRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::ListActiveWorkersResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::ListActiveWorkersRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncListActiveWorkersRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::ListActiveWorkersResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::ListActiveWorkersRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      SynchronizeWorkerState,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::SynchronizeWorkerStateRequest& request,
          ::global_store::SynchronizeWorkerStateResponse* response));
  MOCK_METHOD3(
      AsyncSynchronizeWorkerStateRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::SynchronizeWorkerStateResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::SynchronizeWorkerStateRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncSynchronizeWorkerStateRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::SynchronizeWorkerStateResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::SynchronizeWorkerStateRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      RequestFullStateSync,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::RequestFullStateSyncRequest& request,
          ::global_store::RequestFullStateSyncResponse* response));
  MOCK_METHOD3(
      AsyncRequestFullStateSyncRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::RequestFullStateSyncResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::RequestFullStateSyncRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncRequestFullStateSyncRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::RequestFullStateSyncResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::RequestFullStateSyncRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      HealthCheck,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::HealthCheckRequest& request,
          ::global_store::HealthCheckResponse* response));
  MOCK_METHOD3(
      AsyncHealthCheckRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::HealthCheckResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::HealthCheckRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncHealthCheckRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::HealthCheckResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::HealthCheckRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      QueryChunkLocations,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::QueryChunkLocationsRequest& request,
          ::global_store::QueryChunkLocationsResponse* response));
  MOCK_METHOD3(
      AsyncQueryChunkLocationsRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::QueryChunkLocationsResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::QueryChunkLocationsRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncQueryChunkLocationsRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::QueryChunkLocationsResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::QueryChunkLocationsRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      BatchUpdateChunkStates,
      ::grpc::Status(
          ::grpc::ClientContext* context,
          const ::global_store::BatchUpdateChunkStatesRequest& request,
          ::global_store::BatchUpdateChunkStatesResponse* response));
  MOCK_METHOD3(
      AsyncBatchUpdateChunkStatesRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::BatchUpdateChunkStatesResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::BatchUpdateChunkStatesRequest& request,
          ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(
      PrepareAsyncBatchUpdateChunkStatesRaw,
      ::grpc::ClientAsyncResponseReaderInterface<::global_store::BatchUpdateChunkStatesResponse>*(
          ::grpc::ClientContext* context,
          const ::global_store::BatchUpdateChunkStatesRequest& request,
          ::grpc::CompletionQueue* cq));
};

} // namespace global_store

#endif // GRPC_MOCK_proto_2fglobal_5fstore_2eproto__INCLUDED
