#  Copyright (c) 2025, StepCast Team.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import scstore.proto.global_store_pb2 as global__store__pb2


class GlobalModelStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterModelReplica = channel.unary_unary(
                '/global_store.GlobalModelStore/RegisterModelReplica',
                request_serializer=global__store__pb2.RegisterModelReplicaRequest.SerializeToString,
                response_deserializer=global__store__pb2.RegisterModelReplicaResponse.FromString,
                )
        self.UpdateModelReplica = channel.unary_unary(
                '/global_store.GlobalModelStore/UpdateModelReplica',
                request_serializer=global__store__pb2.UpdateModelReplicaRequest.SerializeToString,
                response_deserializer=global__store__pb2.UpdateModelReplicaResponse.FromString,
                )
        self.UnregisterModelReplica = channel.unary_unary(
                '/global_store.GlobalModelStore/UnregisterModelReplica',
                request_serializer=global__store__pb2.UnregisterModelReplicaRequest.SerializeToString,
                response_deserializer=global__store__pb2.UnregisterModelReplicaResponse.FromString,
                )
        self.RequestModelReplicaTransport = channel.unary_unary(
                '/global_store.GlobalModelStore/RequestModelReplicaTransport',
                request_serializer=global__store__pb2.RequestModelReplicaTransportRequest.SerializeToString,
                response_deserializer=global__store__pb2.RequestModelReplicaTransportResponse.FromString,
                )
        self.CompleteModelReplicaTransport = channel.unary_unary(
                '/global_store.GlobalModelStore/CompleteModelReplicaTransport',
                request_serializer=global__store__pb2.CompleteModelReplicaTransportRequest.SerializeToString,
                response_deserializer=global__store__pb2.CompleteModelReplicaTransportResponse.FromString,
                )
        self.ListModelReplicas = channel.unary_unary(
                '/global_store.GlobalModelStore/ListModelReplicas',
                request_serializer=global__store__pb2.ListModelReplicasRequest.SerializeToString,
                response_deserializer=global__store__pb2.ListModelReplicasResponse.FromString,
                )
        self.GetModelInfo = channel.unary_unary(
                '/global_store.GlobalModelStore/GetModelInfo',
                request_serializer=global__store__pb2.GetModelInfoRequest.SerializeToString,
                response_deserializer=global__store__pb2.GetModelInfoResponse.FromString,
                )
        self.RegisterWorker = channel.unary_unary(
                '/global_store.GlobalModelStore/RegisterWorker',
                request_serializer=global__store__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=global__store__pb2.RegisterWorkerResponse.FromString,
                )
        self.WorkerHeartbeat = channel.unary_unary(
                '/global_store.GlobalModelStore/WorkerHeartbeat',
                request_serializer=global__store__pb2.WorkerHeartbeatRequest.SerializeToString,
                response_deserializer=global__store__pb2.WorkerHeartbeatResponse.FromString,
                )
        self.UnregisterWorker = channel.unary_unary(
                '/global_store.GlobalModelStore/UnregisterWorker',
                request_serializer=global__store__pb2.UnregisterWorkerRequest.SerializeToString,
                response_deserializer=global__store__pb2.UnregisterWorkerResponse.FromString,
                )
        self.ListActiveWorkers = channel.unary_unary(
                '/global_store.GlobalModelStore/ListActiveWorkers',
                request_serializer=global__store__pb2.ListActiveWorkersRequest.SerializeToString,
                response_deserializer=global__store__pb2.ListActiveWorkersResponse.FromString,
                )
        self.SynchronizeWorkerState = channel.unary_unary(
                '/global_store.GlobalModelStore/SynchronizeWorkerState',
                request_serializer=global__store__pb2.SynchronizeWorkerStateRequest.SerializeToString,
                response_deserializer=global__store__pb2.SynchronizeWorkerStateResponse.FromString,
                )
        self.RequestFullStateSync = channel.unary_unary(
                '/global_store.GlobalModelStore/RequestFullStateSync',
                request_serializer=global__store__pb2.RequestFullStateSyncRequest.SerializeToString,
                response_deserializer=global__store__pb2.RequestFullStateSyncResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/global_store.GlobalModelStore/HealthCheck',
                request_serializer=global__store__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=global__store__pb2.HealthCheckResponse.FromString,
                )
        self.QueryChunkLocations = channel.unary_unary(
                '/global_store.GlobalModelStore/QueryChunkLocations',
                request_serializer=global__store__pb2.QueryChunkLocationsRequest.SerializeToString,
                response_deserializer=global__store__pb2.QueryChunkLocationsResponse.FromString,
                )
        self.BatchUpdateChunkStates = channel.unary_unary(
                '/global_store.GlobalModelStore/BatchUpdateChunkStates',
                request_serializer=global__store__pb2.BatchUpdateChunkStatesRequest.SerializeToString,
                response_deserializer=global__store__pb2.BatchUpdateChunkStatesResponse.FromString,
                )


class GlobalModelStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterModelReplica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateModelReplica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterModelReplica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestModelReplicaTransport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteModelReplicaTransport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModelReplicas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """Get model metadata information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterWorker(self, request, context):
        """Worker management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WorkerHeartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListActiveWorkers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SynchronizeWorkerState(self, request, context):
        """High Availability and State Synchronization
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestFullStateSync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check endpoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryChunkLocations(self, request, context):
        """========== Chunk Directory Operations ==========
        Query chunk locations for distributed memory pool
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchUpdateChunkStates(self, request, context):
        """Update chunk states (called by StoreDaemon periodically)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GlobalModelStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterModelReplica': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterModelReplica,
                    request_deserializer=global__store__pb2.RegisterModelReplicaRequest.FromString,
                    response_serializer=global__store__pb2.RegisterModelReplicaResponse.SerializeToString,
            ),
            'UpdateModelReplica': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateModelReplica,
                    request_deserializer=global__store__pb2.UpdateModelReplicaRequest.FromString,
                    response_serializer=global__store__pb2.UpdateModelReplicaResponse.SerializeToString,
            ),
            'UnregisterModelReplica': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterModelReplica,
                    request_deserializer=global__store__pb2.UnregisterModelReplicaRequest.FromString,
                    response_serializer=global__store__pb2.UnregisterModelReplicaResponse.SerializeToString,
            ),
            'RequestModelReplicaTransport': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestModelReplicaTransport,
                    request_deserializer=global__store__pb2.RequestModelReplicaTransportRequest.FromString,
                    response_serializer=global__store__pb2.RequestModelReplicaTransportResponse.SerializeToString,
            ),
            'CompleteModelReplicaTransport': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteModelReplicaTransport,
                    request_deserializer=global__store__pb2.CompleteModelReplicaTransportRequest.FromString,
                    response_serializer=global__store__pb2.CompleteModelReplicaTransportResponse.SerializeToString,
            ),
            'ListModelReplicas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModelReplicas,
                    request_deserializer=global__store__pb2.ListModelReplicasRequest.FromString,
                    response_serializer=global__store__pb2.ListModelReplicasResponse.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=global__store__pb2.GetModelInfoRequest.FromString,
                    response_serializer=global__store__pb2.GetModelInfoResponse.SerializeToString,
            ),
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=global__store__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=global__store__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'WorkerHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.WorkerHeartbeat,
                    request_deserializer=global__store__pb2.WorkerHeartbeatRequest.FromString,
                    response_serializer=global__store__pb2.WorkerHeartbeatResponse.SerializeToString,
            ),
            'UnregisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterWorker,
                    request_deserializer=global__store__pb2.UnregisterWorkerRequest.FromString,
                    response_serializer=global__store__pb2.UnregisterWorkerResponse.SerializeToString,
            ),
            'ListActiveWorkers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListActiveWorkers,
                    request_deserializer=global__store__pb2.ListActiveWorkersRequest.FromString,
                    response_serializer=global__store__pb2.ListActiveWorkersResponse.SerializeToString,
            ),
            'SynchronizeWorkerState': grpc.unary_unary_rpc_method_handler(
                    servicer.SynchronizeWorkerState,
                    request_deserializer=global__store__pb2.SynchronizeWorkerStateRequest.FromString,
                    response_serializer=global__store__pb2.SynchronizeWorkerStateResponse.SerializeToString,
            ),
            'RequestFullStateSync': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestFullStateSync,
                    request_deserializer=global__store__pb2.RequestFullStateSyncRequest.FromString,
                    response_serializer=global__store__pb2.RequestFullStateSyncResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=global__store__pb2.HealthCheckRequest.FromString,
                    response_serializer=global__store__pb2.HealthCheckResponse.SerializeToString,
            ),
            'QueryChunkLocations': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryChunkLocations,
                    request_deserializer=global__store__pb2.QueryChunkLocationsRequest.FromString,
                    response_serializer=global__store__pb2.QueryChunkLocationsResponse.SerializeToString,
            ),
            'BatchUpdateChunkStates': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchUpdateChunkStates,
                    request_deserializer=global__store__pb2.BatchUpdateChunkStatesRequest.FromString,
                    response_serializer=global__store__pb2.BatchUpdateChunkStatesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'global_store.GlobalModelStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GlobalModelStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterModelReplica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/global_store.GlobalModelStore/RegisterModelReplica',
            global__store__pb2.RegisterModelReplicaRequest.SerializeToString,
            global__store__pb2.RegisterModelReplicaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateModelReplica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/global_store.GlobalModelStore/UpdateModelReplica',
            global__store__pb2.UpdateModelReplicaRequest.SerializeToString,
            global__store__pb2.UpdateModelReplicaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnregisterModelReplica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/global_store.GlobalModelStore/UnregisterModelReplica',
            global__store__pb2.UnregisterModelReplicaRequest.SerializeToString,
            global__store__pb2.UnregisterModelReplicaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestModelReplicaTransport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/global_store.GlobalModelStore/RequestModelReplicaTransport',
            global__store__pb2.RequestModelReplicaTransportRequest.SerializeToString,
            global__store__pb2.RequestModelReplicaTransportResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CompleteModelReplicaTransport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/global_store.GlobalModelStore/CompleteModelReplicaTransport',
            global__store__pb2.CompleteModelReplicaTransportRequest.SerializeToString,
            global__store__pb2.CompleteModelReplicaTransportResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListModelReplicas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/global_store.GlobalModelStore/ListModelReplicas',
            global__store__pb2.ListModelReplicasRequest.SerializeToString,
            global__store__pb2.ListModelReplicasResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/global_store.GlobalModelStore/GetModelInfo',
            global__store__pb2.GetModelInfoRequest.SerializeToString,
            global__store__pb2.GetModelInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/global_store.GlobalModelStore/RegisterWorker',
            global__store__pb2.RegisterWorkerRequest.SerializeToString,
            global__store__pb2.RegisterWorkerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WorkerHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/global_store.GlobalModelStore/WorkerHeartbeat',
            global__store__pb2.WorkerHeartbeatRequest.SerializeToString,
            global__store__pb2.WorkerHeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnregisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/global_store.GlobalModelStore/UnregisterWorker',
            global__store__pb2.UnregisterWorkerRequest.SerializeToString,
            global__store__pb2.UnregisterWorkerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListActiveWorkers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/global_store.GlobalModelStore/ListActiveWorkers',
            global__store__pb2.ListActiveWorkersRequest.SerializeToString,
            global__store__pb2.ListActiveWorkersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SynchronizeWorkerState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/global_store.GlobalModelStore/SynchronizeWorkerState',
            global__store__pb2.SynchronizeWorkerStateRequest.SerializeToString,
            global__store__pb2.SynchronizeWorkerStateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestFullStateSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/global_store.GlobalModelStore/RequestFullStateSync',
            global__store__pb2.RequestFullStateSyncRequest.SerializeToString,
            global__store__pb2.RequestFullStateSyncResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/global_store.GlobalModelStore/HealthCheck',
            global__store__pb2.HealthCheckRequest.SerializeToString,
            global__store__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryChunkLocations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/global_store.GlobalModelStore/QueryChunkLocations',
            global__store__pb2.QueryChunkLocationsRequest.SerializeToString,
            global__store__pb2.QueryChunkLocationsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BatchUpdateChunkStates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/global_store.GlobalModelStore/BatchUpdateChunkStates',
            global__store__pb2.BatchUpdateChunkStatesRequest.SerializeToString,
            global__store__pb2.BatchUpdateChunkStatesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
