#  Copyright (c) 2025, StepCast Team.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

import scstore.proto.store_daemon_pb2 as store__daemon__pb2


class StoreDaemonStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoadModel = channel.unary_unary(
            "/store_daemon.StoreDaemon/LoadModel",
            request_serializer=store__daemon__pb2.LoadModelRequest.SerializeToString,
            response_deserializer=store__daemon__pb2.LoadModelResponse.FromString,
        )
        self.ConfirmModel = channel.unary_unary(
            "/store_daemon.StoreDaemon/ConfirmModel",
            request_serializer=store__daemon__pb2.ConfirmModelRequest.SerializeToString,
            response_deserializer=store__daemon__pb2.ConfirmModelResponse.FromString,
        )
        self.UnloadModel = channel.unary_unary(
            "/store_daemon.StoreDaemon/UnloadModel",
            request_serializer=store__daemon__pb2.UnloadModelRequest.SerializeToString,
            response_deserializer=store__daemon__pb2.UnloadModelResponse.FromString,
        )
        self.ClearMem = channel.unary_unary(
            "/store_daemon.StoreDaemon/ClearMem",
            request_serializer=store__daemon__pb2.ClearMemRequest.SerializeToString,
            response_deserializer=store__daemon__pb2.ClearMemResponse.FromString,
        )
        self.GetServerConfig = channel.unary_unary(
            "/store_daemon.StoreDaemon/GetServerConfig",
            request_serializer=store__daemon__pb2.GetServerConfigRequest.SerializeToString,
            response_deserializer=store__daemon__pb2.GetServerConfigResponse.FromString,
        )
        self.GetWorkerStatus = channel.unary_unary(
            "/store_daemon.StoreDaemon/GetWorkerStatus",
            request_serializer=store__daemon__pb2.GetWorkerStatusRequest.SerializeToString,
            response_deserializer=store__daemon__pb2.GetWorkerStatusResponse.FromString,
        )
        self.WaitModelVerification = channel.unary_unary(
            "/store_daemon.StoreDaemon/WaitModelVerification",
            request_serializer=store__daemon__pb2.VerificationRequest.SerializeToString,
            response_deserializer=store__daemon__pb2.VerificationResponse.FromString,
        )
        self.GetDetailedStatus = channel.unary_unary(
            "/store_daemon.StoreDaemon/GetDetailedStatus",
            request_serializer=store__daemon__pb2.GetDetailedStatusRequest.SerializeToString,
            response_deserializer=store__daemon__pb2.GetDetailedStatusResponse.FromString,
        )
        self.GetLoadedModels = channel.unary_unary(
            "/store_daemon.StoreDaemon/GetLoadedModels",
            request_serializer=store__daemon__pb2.GetLoadedModelsRequest.SerializeToString,
            response_deserializer=store__daemon__pb2.GetLoadedModelsResponse.FromString,
        )
        self.LockTransportChunks = channel.unary_unary(
            "/store_daemon.StoreDaemon/LockTransportChunks",
            request_serializer=store__daemon__pb2.LockChunksRequest.SerializeToString,
            response_deserializer=store__daemon__pb2.LockChunksResponse.FromString,
        )
        self.UnlockTransportChunks = channel.unary_unary(
            "/store_daemon.StoreDaemon/UnlockTransportChunks",
            request_serializer=store__daemon__pb2.UnlockChunksRequest.SerializeToString,
            response_deserializer=store__daemon__pb2.UnlockChunksResponse.FromString,
        )
        self.BeginRegisterTensorDict = channel.unary_unary(
            "/store_daemon.StoreDaemon/BeginRegisterTensorDict",
            request_serializer=store__daemon__pb2.BeginRegisterTensorDictRequest.SerializeToString,
            response_deserializer=store__daemon__pb2.BeginRegisterTensorDictResponse.FromString,
        )
        self.CommitRegisteredTensorDict = channel.unary_unary(
            "/store_daemon.StoreDaemon/CommitRegisteredTensorDict",
            request_serializer=store__daemon__pb2.CommitRegisteredTensorDictRequest.SerializeToString,
            response_deserializer=store__daemon__pb2.CommitRegisteredTensorDictResponse.FromString,
        )
        self.AbortRegisteredTensorDict = channel.unary_unary(
            "/store_daemon.StoreDaemon/AbortRegisteredTensorDict",
            request_serializer=store__daemon__pb2.AbortRegisteredTensorDictRequest.SerializeToString,
            response_deserializer=store__daemon__pb2.AbortRegisteredTensorDictResponse.FromString,
        )


class StoreDaemonServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LoadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ConfirmModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UnloadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ClearMem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetServerConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetWorkerStatus(self, request, context):
        """Worker健康检测"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def WaitModelVerification(self, request, context):
        """------------------------------------------------------------------
        Asynchronous model integrity verification support.  Each LoadModel
        request triggers a background verification task on the daemon side.
        Clients can poll/wait for the outcome via this RPC.
        ------------------------------------------------------------------

        Wait until the daemon finishes verifying the specified model replica
        (identified by the <model_identifier, replica_uuid> tuple) or the
        provided timeout elapses.  The call returns the current verification
        status so that clients can decide whether to retry or abort.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetDetailedStatus(self, request, context):
        """获取详细状态信息"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetLoadedModels(self, request, context):
        """Get reference information for all loaded models"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def LockTransportChunks(self, request, context):
        """========== Distributed chunk locking ==========
        Dual-end locking mechanism for P2P transfers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UnlockTransportChunks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def BeginRegisterTensorDict(self, request, context):
        """========== Memory TensorDict Registration ==========
        Register in-memory tensor dict as memory replica without disk I/O
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CommitRegisteredTensorDict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AbortRegisteredTensorDict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_StoreDaemonServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "LoadModel": grpc.unary_unary_rpc_method_handler(
            servicer.LoadModel,
            request_deserializer=store__daemon__pb2.LoadModelRequest.FromString,
            response_serializer=store__daemon__pb2.LoadModelResponse.SerializeToString,
        ),
        "ConfirmModel": grpc.unary_unary_rpc_method_handler(
            servicer.ConfirmModel,
            request_deserializer=store__daemon__pb2.ConfirmModelRequest.FromString,
            response_serializer=store__daemon__pb2.ConfirmModelResponse.SerializeToString,
        ),
        "UnloadModel": grpc.unary_unary_rpc_method_handler(
            servicer.UnloadModel,
            request_deserializer=store__daemon__pb2.UnloadModelRequest.FromString,
            response_serializer=store__daemon__pb2.UnloadModelResponse.SerializeToString,
        ),
        "ClearMem": grpc.unary_unary_rpc_method_handler(
            servicer.ClearMem,
            request_deserializer=store__daemon__pb2.ClearMemRequest.FromString,
            response_serializer=store__daemon__pb2.ClearMemResponse.SerializeToString,
        ),
        "GetServerConfig": grpc.unary_unary_rpc_method_handler(
            servicer.GetServerConfig,
            request_deserializer=store__daemon__pb2.GetServerConfigRequest.FromString,
            response_serializer=store__daemon__pb2.GetServerConfigResponse.SerializeToString,
        ),
        "GetWorkerStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetWorkerStatus,
            request_deserializer=store__daemon__pb2.GetWorkerStatusRequest.FromString,
            response_serializer=store__daemon__pb2.GetWorkerStatusResponse.SerializeToString,
        ),
        "WaitModelVerification": grpc.unary_unary_rpc_method_handler(
            servicer.WaitModelVerification,
            request_deserializer=store__daemon__pb2.VerificationRequest.FromString,
            response_serializer=store__daemon__pb2.VerificationResponse.SerializeToString,
        ),
        "GetDetailedStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetDetailedStatus,
            request_deserializer=store__daemon__pb2.GetDetailedStatusRequest.FromString,
            response_serializer=store__daemon__pb2.GetDetailedStatusResponse.SerializeToString,
        ),
        "GetLoadedModels": grpc.unary_unary_rpc_method_handler(
            servicer.GetLoadedModels,
            request_deserializer=store__daemon__pb2.GetLoadedModelsRequest.FromString,
            response_serializer=store__daemon__pb2.GetLoadedModelsResponse.SerializeToString,
        ),
        "LockTransportChunks": grpc.unary_unary_rpc_method_handler(
            servicer.LockTransportChunks,
            request_deserializer=store__daemon__pb2.LockChunksRequest.FromString,
            response_serializer=store__daemon__pb2.LockChunksResponse.SerializeToString,
        ),
        "UnlockTransportChunks": grpc.unary_unary_rpc_method_handler(
            servicer.UnlockTransportChunks,
            request_deserializer=store__daemon__pb2.UnlockChunksRequest.FromString,
            response_serializer=store__daemon__pb2.UnlockChunksResponse.SerializeToString,
        ),
        "BeginRegisterTensorDict": grpc.unary_unary_rpc_method_handler(
            servicer.BeginRegisterTensorDict,
            request_deserializer=store__daemon__pb2.BeginRegisterTensorDictRequest.FromString,
            response_serializer=store__daemon__pb2.BeginRegisterTensorDictResponse.SerializeToString,
        ),
        "CommitRegisteredTensorDict": grpc.unary_unary_rpc_method_handler(
            servicer.CommitRegisteredTensorDict,
            request_deserializer=store__daemon__pb2.CommitRegisteredTensorDictRequest.FromString,
            response_serializer=store__daemon__pb2.CommitRegisteredTensorDictResponse.SerializeToString,
        ),
        "AbortRegisteredTensorDict": grpc.unary_unary_rpc_method_handler(
            servicer.AbortRegisteredTensorDict,
            request_deserializer=store__daemon__pb2.AbortRegisteredTensorDictRequest.FromString,
            response_serializer=store__daemon__pb2.AbortRegisteredTensorDictResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "store_daemon.StoreDaemon", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class StoreDaemon(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LoadModel(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/store_daemon.StoreDaemon/LoadModel",
            store__daemon__pb2.LoadModelRequest.SerializeToString,
            store__daemon__pb2.LoadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ConfirmModel(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/store_daemon.StoreDaemon/ConfirmModel",
            store__daemon__pb2.ConfirmModelRequest.SerializeToString,
            store__daemon__pb2.ConfirmModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def UnloadModel(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/store_daemon.StoreDaemon/UnloadModel",
            store__daemon__pb2.UnloadModelRequest.SerializeToString,
            store__daemon__pb2.UnloadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ClearMem(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/store_daemon.StoreDaemon/ClearMem",
            store__daemon__pb2.ClearMemRequest.SerializeToString,
            store__daemon__pb2.ClearMemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetServerConfig(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/store_daemon.StoreDaemon/GetServerConfig",
            store__daemon__pb2.GetServerConfigRequest.SerializeToString,
            store__daemon__pb2.GetServerConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetWorkerStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/store_daemon.StoreDaemon/GetWorkerStatus",
            store__daemon__pb2.GetWorkerStatusRequest.SerializeToString,
            store__daemon__pb2.GetWorkerStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def WaitModelVerification(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/store_daemon.StoreDaemon/WaitModelVerification",
            store__daemon__pb2.VerificationRequest.SerializeToString,
            store__daemon__pb2.VerificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetDetailedStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/store_daemon.StoreDaemon/GetDetailedStatus",
            store__daemon__pb2.GetDetailedStatusRequest.SerializeToString,
            store__daemon__pb2.GetDetailedStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetLoadedModels(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/store_daemon.StoreDaemon/GetLoadedModels",
            store__daemon__pb2.GetLoadedModelsRequest.SerializeToString,
            store__daemon__pb2.GetLoadedModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def LockTransportChunks(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/store_daemon.StoreDaemon/LockTransportChunks",
            store__daemon__pb2.LockChunksRequest.SerializeToString,
            store__daemon__pb2.LockChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def UnlockTransportChunks(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/store_daemon.StoreDaemon/UnlockTransportChunks",
            store__daemon__pb2.UnlockChunksRequest.SerializeToString,
            store__daemon__pb2.UnlockChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def BeginRegisterTensorDict(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/store_daemon.StoreDaemon/BeginRegisterTensorDict",
            store__daemon__pb2.BeginRegisterTensorDictRequest.SerializeToString,
            store__daemon__pb2.BeginRegisterTensorDictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def CommitRegisteredTensorDict(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/store_daemon.StoreDaemon/CommitRegisteredTensorDict",
            store__daemon__pb2.CommitRegisteredTensorDictRequest.SerializeToString,
            store__daemon__pb2.CommitRegisteredTensorDictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def AbortRegisteredTensorDict(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/store_daemon.StoreDaemon/AbortRegisteredTensorDict",
            store__daemon__pb2.AbortRegisteredTensorDictRequest.SerializeToString,
            store__daemon__pb2.AbortRegisteredTensorDictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
