// Copyright (c) 2025-2026, TensorCast Team.

#include <catch2/catch_test_macros.hpp>

#include <filesystem>
#include <fstream>
#include <stdexcept>
#include <string>

#include <nlohmann/json.hpp>

#include "absl/status/status.h"
#include "core/common/artifact_verification.h"
#include "core/store/store_engine.h"
#include "core/store/store_engine_options.h"
#include "core/testing/common.h"

namespace fs = std::filesystem;
using tensorcast::DeviceType;
using tensorcast::store::DeviceKey;
using tensorcast::store::StoreEngine;
using tensorcast::store::StoreEngineOptions;
using tensorcast::store::loading::DiskSource;

static StoreEngine make_store(const fs::path& root) {
  StoreEngineOptions opts;
  opts.storage_path = root.string();
  opts.memory_pool_size = 32ULL * 1024 * 1024;
  opts.tx_slice_bytes = 64ULL * 1024;
  opts.num_thread = 2;
  opts.pinned_memory_timeout = std::chrono::milliseconds(0);
  return StoreEngine(opts);
}

static DeviceKey cpu_key() {
  return DeviceKey{DeviceType::CPU, -1, /*uuid=*/""};
}

static std::string read_descriptor_artifact_id(const fs::path& artifact_dir) {
  const auto descriptor_path = artifact_dir / "artifact_descriptor.json";
  std::ifstream in(descriptor_path);
  if (!in.is_open()) {
    throw std::runtime_error("failed to open artifact_descriptor.json");
  }
  nlohmann::json j;
  in >> j;
  return j.at("artifact_id").get<std::string>();
}

TEST_CASE("Post-load verification generation and enforcement", "[store_engine][verification]") {
  const std::string artifact_name = "verify_artifact";
  const size_t artifact_size = 128 * 1024; // 128 KiB

  fs::path temp_root = fs::temp_directory_path() / "store_engine_verify_default_test";
  fs::create_directories(temp_root);
  fs::path artifact_dir = temp_root / artifact_name;
  fs::create_directories(artifact_dir);

  // Create data and descriptor (standard partitions format)
  REQUIRE(tensorcast::testing::create_dummy_file(artifact_dir / "tensor.data", artifact_size));
  REQUIRE(tensorcast::testing::write_rfc0007_descriptor_for_standard_artifact_dir(artifact_dir).ok());
  const std::string artifact_id = read_descriptor_artifact_id(artifact_dir);

  // Ensure verification.json does not exist initially
  fs::path verification_path = artifact_dir / "verification.json";
  if (fs::exists(verification_path)) {
    fs::remove(verification_path);
  }

  // Load to CPU and wait ready
  StoreEngine store = make_store(temp_root);
  tensorcast::store::loading::MaterializeHints hints;
  hints.artifact_id = artifact_id;
  DiskSource disk_source{.path = artifact_dir, .expected_size = std::nullopt};
  auto handle_or = store.materialize_replica(
      cpu_key(), tensorcast::store::StoreEngine::MaterializeMode::LOAD_ONLY, hints, disk_source);
  REQUIRE(handle_or.ok());
  if (!handle_or.ok()) {
    LOG(ERROR) << "Materialize failed: " << handle_or.status().message();
  }
  auto handle = std::move(*handle_or);
  REQUIRE(handle.wait_ready(std::chrono::milliseconds(30000)).ok());

  // Verify that verification.json is generated by default
  REQUIRE(fs::exists(verification_path));

  // Prepare a directory with a deliberately mismatching verification.json
  const std::string artifact_name2 = "verify_artifact_bad";
  const size_t artifact_size2 = artifact_size + 1;
  fs::path artifact_dir2 = temp_root / artifact_name2;
  fs::create_directories(artifact_dir2);
  REQUIRE(tensorcast::testing::create_dummy_file(artifact_dir2 / "tensor.data", artifact_size2));
  REQUIRE(tensorcast::testing::write_rfc0007_descriptor_for_standard_artifact_dir(artifact_dir2).ok());
  const std::string artifact_id2 = read_descriptor_artifact_id(artifact_dir2);
  REQUIRE(artifact_id2 != artifact_id);

  // Write a bad verification.json (wrong key_values ensures failure)
  tensorcast::common::ArtifactVerificationInfo bad_info;
  bad_info.artifact_size = artifact_size2;
  bad_info.full_hash = 0ULL;
  bad_info.segment_hashes.fill(0ULL);
  bad_info.sample_values.fill(0ULL);
  bad_info.key_values = {1ULL, 2ULL, 3ULL};
  bad_info.refresh_metadata_signature();
  std::ofstream out(artifact_dir2 / "verification.json");
  REQUIRE(out.is_open());
  out << bad_info.to_json();
  out.close();

  tensorcast::store::loading::MaterializeHints hints2;
  hints2.artifact_id = artifact_id2;
  DiskSource disk_source2{.path = artifact_dir2, .expected_size = std::nullopt};
  auto handle_or2 = store.materialize_replica(
      cpu_key(), tensorcast::store::StoreEngine::MaterializeMode::LOAD_ONLY, hints2, disk_source2);
  REQUIRE_FALSE(handle_or2.ok());

  std::error_code ec;
  fs::remove_all(temp_root, ec);
}
